### PR TITLE
mdnsd: remove mhttp reference, don't munge a-record hostname (foo.local)

### LINKED ISSUE #3: usage description wrong
Hey,

just a minor wrong printf in the usage description. In line 92 of mdnsd.c it still says mhttp. To get rid of it for all time, you could make
printf("usage: %s 'unique name' 12.34.56.78 80 '/optionalpath'\n", argv[0]);

Best regards

### LINKED ISSUE #4: autogen.sh fails with "'LIBTOOL' is undefined"
Apologies if I'm doing something obviously wrong, I'm not well versed in native linux development.

```
# ./autogen.sh 
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force --warnings=portability -I m4
autoreconf: configure.ac: tracing
autoreconf: configure.ac: not using Libtool
autoreconf: running: /usr/bin/autoconf --force --warnings=portability
autoreconf: running: /usr/bin/autoheader --force --warnings=portability
autoreconf: running: automake --add-missing --force-missing --warnings=portability
libmdnsd/Makefile.am:1: error: Libtool library used but 'LIBTOOL' is undefined
libmdnsd/Makefile.am:1:   The usual way to define 'LIBTOOL' is to add 'LT_INIT'
libmdnsd/Makefile.am:1:   to 'configure.ac' and run 'aclocal' and 'autoconf' again.
libmdnsd/Makefile.am:1:   If 'LT_INIT' is in 'configure.ac', make sure
libmdnsd/Makefile.am:1:   its definition is in aclocal's search path.
autoreconf: automake failed with exit status: 1

# uname -a
Linux 3a10646176c4 4.9.87-linuxkit-aufs #1 SMP Wed Mar 14 15:12:16 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

### PR DESCRIPTION
**Pull request by thom-nic**
Fixes #3 
Fixes #4

### CODE REVIEW

**Comment by thom-nic** [comment]
Funny enough this does not conflict with #1

File: mdnsd.c [hunk 1]
```diff
@@ -161,6 +161,9 @@ int main(int argc, char *argv[])
 				printf("can't write to socket: %s\n", strerror(errno));
 				return 1;
 			}
+			else {
```
Comment (troglobit) [inline mdnsd.c]: Minor nitpick, the coding style is Linux, so else's should be cuddled, like this `} else {`. But I'm gonna merge anyway and fix later :)

**Comment by troglobit** [comment]
Awesome work!  Yeah, #1 has drifted a bit too far from the original to be possible to merge as-is.  I've considered cherry-picking a few of the commits, that's the only reason it's still open.
